/*
 * generated by Xtext
 */
package org.uqbar.paco.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTortugaDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.uqbar.paco.dsl.tortugaDSL.TortugaDSLPackage.eINSTANCE);
		return result;
	}
}
