/*
* generated by Xtext
*/
package org.uqbar.paco.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TortugaDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/uqbar/paco/dsl/parser/antlr/internal/InternalTortugaDSL.tokens");
	}
}
