/*
* generated by Xtext
*/
package org.uqbar.paco.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TortugaDSLStandaloneSetup extends TortugaDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new TortugaDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

