/*
 * generated by Xtext
 */
package org.uqbar.paco.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TortugaDSLRuntimeModule extends org.uqbar.paco.dsl.AbstractTortugaDSLRuntimeModule {

}
