/**
 * generated by Xtext
 */
package org.uqbar.paco.dsl.validation;

import org.uqbar.paco.dsl.validation.AbstractTortugaDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TortugaDSLValidator extends AbstractTortugaDSLValidator {
}
