/**
 * generated by Xtext
 */
package org.uqbar.paco.dsl.ui.contentassist;

import org.uqbar.paco.dsl.ui.contentassist.AbstractTortugaDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TortugaDSLProposalProvider extends AbstractTortugaDSLProposalProvider {
}
