/*
 * generated by Xtext
 */
package org.uqbar.paco.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TortugaDSLUiModule extends org.uqbar.paco.dsl.ui.AbstractTortugaDSLUiModule {
	public TortugaDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
